# Generated by Django 4.2.7 on 2023-11-02 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vender',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vender', to=settings.AUTH_USER_MODEL),
        ),
    ]
